name: vision-zoo
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - astroid=2.14.2=py310hff52083_0
  - black=23.1.0=py310hff52083_0
  - blas=2.116=mkl
  - blas-devel=3.9.0=16_linux64_mkl
  - brotlipy=0.7.0=py310h5764c6d_1005
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.12.7=ha878542_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py310h255011f_3
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - colorama=0.4.6=pyhd8ed1ab_0
  - cryptography=39.0.2=py310h34c0648_0
  - cudatoolkit=11.6.0=habf752d_9
  - dill=0.3.6=pyhd8ed1ab_1
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.9.0=pyhd8ed1ab_0
  - freetype=2.12.1=hca18f0e_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - huggingface_hub=0.12.1=pyhd8ed1ab_0
  - icu=70.1=h27087fc_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.0.0=pyha770c72_0
  - isort=5.12.0=pyhd8ed1ab_1
  - jpeg=9e=h0b41bf4_3
  - lame=3.100=h166bdaf_1003
  - lazy-object-proxy=1.9.0=py310h1fa729e_0
  - lcms2=2.14=hfd0df8a_1
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=16_linux64_mkl
  - libcblas=3.9.0=16_linux64_mkl
  - libdeflate=1.17=h0b41bf4_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libhwloc=2.9.0=hd6dc26d_0
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.9.0=16_linux64_mkl
  - liblapacke=3.9.0=16_linux64_mkl
  - libnsl=2.0.0=h7f98852_0
  - libpng=1.6.39=h753d276_0
  - libsqlite=3.40.0=h753d276_0
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtiff=4.5.0=h6adf6a1_2
  - libuuid=2.32.1=h7f98852_1000
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.10.3=h7463322_0
  - libzlib=1.2.13=h166bdaf_4
  - llvm-openmp=15.0.7=h0cdce71_0
  - mccabe=0.7.0=pyhd8ed1ab_0
  - mkl=2022.1.0=h84fe81f_915
  - mkl-devel=2022.1.0=ha770c72_916
  - mkl-include=2022.1.0=h84fe81f_915
  - mypy_extensions=1.0.0=pyha770c72_0
  - ncurses=6.3=h27087fc_1
  - nettle=3.6=he412f7d_0
  - numpy=1.24.2=py310h8deb116_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.0.8=h0b41bf4_0
  - packaging=23.0=pyhd8ed1ab_0
  - pathspec=0.11.0=pyhd8ed1ab_0
  - pillow=9.4.0=py310h023d228_1
  - pip=23.0.1=pyhd8ed1ab_0
  - platformdirs=3.0.0=pyhd8ed1ab_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pycparser=2.21=pyhd8ed1ab_0
  - pylint=2.16.3=pyhd8ed1ab_0
  - pyopenssl=23.0.0=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.9=he550d4f_0_cpython
  - python_abi=3.10=3_cp310
  - pytorch=1.12.1=py3.10_cuda11.6_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0=py310h5764c6d_5
  - readline=8.1.2=h0f457ee_0
  - requests=2.28.2=pyhd8ed1ab_0
  - setuptools=67.4.0=pyhd8ed1ab_0
  - tbb=2021.8.0=hf52228f_0
  - termcolor=2.2.0=pyhd8ed1ab_0
  - timm=0.6.12=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomlkit=0.11.6=pyha770c72_0
  - torchvision=0.13.1=py310_cu116
  - tqdm=4.64.1=pyhd8ed1ab_0
  - typing=3.10.0.0=pyhd8ed1ab_0
  - typing-extensions=4.4.0=hd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - tzdata=2022g=h191b570_0
  - urllib3=1.26.14=pyhd8ed1ab_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - wrapt=1.15.0=py310h1fa729e_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.6=h166bdaf_0
  - yacs=0.1.8=pyhd8ed1ab_0
  - yaml=0.2.5=h7f98852_2
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=h3eb15da_6
  - pip:
      - appdirs==1.4.4
      - contourpy==1.0.7
      - cycler==0.11.0
      - docker-pycreds==0.4.0
      - fonttools==4.38.0
      - fvcore==0.1.5.post20221221
      - gitdb==4.0.10
      - gitpython==3.1.31
      - h5py==3.8.0
      - iopath==0.1.10
      - kiwisolver==1.4.4
      - matplotlib==3.7.0
      - pathtools==0.1.2
      - portalocker==2.7.0
      - protobuf==4.22.1
      - psutil==5.9.4
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - sentry-sdk==1.16.0
      - setproctitle==1.3.2
      - six==1.16.0
      - smmap==5.0.0
      - tabulate==0.9.0
      - wandb==0.13.11
prefix: /home/narisam/miniconda3/envs/vision-zoo
