AUG:
  COLOR_JITTER: 0.4
DATA:
  BATCH_SIZE: 256
  DATASET: "cifar10"
  IMG_SIZE: 32
  NUM_WORKERS: 32
  PIN_MEMORY: True
MODEL:
  NAME: lenet
  NUM_CLASSES: 200
  DROP_RATE: 0.0
TRAIN:
  EPOCHS: 50
  WARMUP_EPOCHS: 10
  LR: 3e-4
  MIN_LR: 3e-5
  WARMUP_LR: 3e-5
  LR_SCHEDULER:
    NAME: "cosine"
  OPTIMIZER:
    NAME: "adamw"
    EPS: 1e-8
    BETAS: (0.9, 0.999)
    MOMENTUM: 0.9
OUTPUT: "output/lenet_cifar"
SAVE_FREQ: 5
PRINT_FREQ: 99999
PRINT_FREQ: 99999